package com.moon.quizfish

class Const {
    val thumbnail = arrayOf(
        R.drawable.a1,
        R.drawable.a2,
        R.drawable.a3,
        R.drawable.a4,
        R.drawable.a5,
        R.drawable.a6,
        R.drawable.a7,
        R.drawable.a8,
        R.drawable.a9,
        R.drawable.a10,
        R.drawable.a11,
        R.drawable.a12,
        R.drawable.a13,
        R.drawable.a14,
        R.drawable.a15,
        R.drawable.a16,
        R.drawable.a17,
        R.drawable.a18,
        R.drawable.a19,
        R.drawable.a20,
        R.drawable.a21,
        R.drawable.a22,
        R.drawable.a23,
        R.drawable.a24,
        R.drawable.a25,
        R.drawable.a26,
        R.drawable.a27,
        R.drawable.a28,
        R.drawable.a29,
        R.drawable.a30,
        R.drawable.a31,
        R.drawable.a32,
        R.drawable.a33,
        R.drawable.a34,
        R.drawable.a35,
        R.drawable.a36,
        R.drawable.a37,
        R.drawable.a38,
        R.drawable.a39,
        R.drawable.a40
    )

    val name = arrayOf(
        "잉어",
        "금붕어",
        "오스카",
        "웰스메기",
        "잰더",
        "유럽농어",
        "노던파이크",
        "황새치",
        "무지개송어",
        "닥터피쉬",
        "얼룩말 물고기",
        "네온 테트라",
        "구피",
        "샴투어",
        "몰리",
        "제브라다니오",
        "엔젤 피쉬",
        "모래무지",
        "미우루스 복어",
        "철갑 상어",
        "다금바리",
        "민어",
        "참치방어",
        "흑돔",
        "병어",
        "은갈치",
        "망둥어",
        "장갱이",
        "붕장어",
        "보리멸",
        "노래미",
        "보구치",
        "문치 가자미",
        "황어",
        "돌우럭",
        "쏨뱅이",
        "성대",
        "쥐치",
        "횟대",
        "삼세기"
    )
}